services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        POSTGRES_HOST: postgres
    image: node:20
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - fcl_project
    environment:
      DB_PORT: 5432:5432
      DB_USERNAME: postgres
      DB_NAME: FCL
      DATABASE_URL: ${DATABASE_URL}


  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - fcl_project

volumes:
  fcl-project-data:

networks:
  fcl_project: