services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:20
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://$DB_USER@postgres:$DB_PORT/$DB_NAME?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30"


  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  fcl-project-data: